### ISSUE TITLE
Golang PE binaries, symbols in wrong locations

### ISSUE THREAD

**Issue by dev747368** [cyberkaida/golang-ghidra#3]
You had an issue with symbols not being in correct locations in a PE binary.  (firstmoduledata)

There was an issue that was fixed, but it doesn't seem to be included in a release yet.

The binary had 2 .data sections.  This is a bit of a ghidra-ism.  The first one is the initialized part of the .data, and the second one was for the uninitialized portion of the section.

When PE debug symbols were being laid down, the wrong section was being picked as the base address for the label symbol, so you would get the label at offset 1234 of the second  (uninitialized) .data section instead of at offset 1234 of the first .data section.

**Comment by dev747368** [comment]
This was the commit that fixed it.  https://github.com/NationalSecurityAgency/ghidra/commit/dba70df2affbdfe1855b66cb7fa1fc4dcfde85e7

**Comment by cyberkaida** [comment]
Thank you very much for the info! I think I have a work around for this issue, but I will note this in a comment and remove the work around when Ghidra is updated.

**Comment by cyberkaida** [comment]
This is a fix for issue https://github.com/NationalSecurityAgency/ghidra/issues/4815

**Comment by cyberkaida** [comment]
The fix is scheduled for 10.2.3: https://github.com/NationalSecurityAgency/ghidra/milestone/29

**Comment by cyberkaida** [comment]
It appears this has landed in 10.2.3. I will try this again and remove my hack when on that version or above. Thanks @dev747368 !
